### ISSUE TITLE
Executables hashbang header not portable

### ISSUE THREAD

**Issue by luciorq** [pedrohdemedeiros/scripts_mestrado#1]
Oi @pedrohdemedeiros, muito bacana seu projeto aqui.

Esbarrei no seu [post no LinkedIn](https://www.linkedin.com/posts/pedroh-medeiros_existe-uma-barreira-que-leva-os-estudantes-activity-7108568305971425280-jJeL) e acho bom colaborar com a comunidade de Bioinfoinformática brasileira.

Uma dica simples no cabeçalho dos seus Shell Scripts é usar `#!/usr/bin/env bash` no lugar de `#!/bin/bash` ou `#!/bin/usr/bash`. 

Isto torna seus scripts mais portáveis como executáveis. O mesmo vale para python ou outros scripts em geral.
Nem todos os sistema operacionais e distribuições colocam o Bash no mesmo caminho.

Obrigado pelo material!

**Comment by pedrohdemedeiros** [comment]
Valeu, Lúcio! Vou implementar e atualizar!

Abraços!
